// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.epam.com/ryan_wang/go-web-service/internal/config"
	"git.epam.com/ryan_wang/go-web-service/internal/domains/record"
	"git.epam.com/ryan_wang/go-web-service/internal/web"
)

// Injectors from wire.go:

func InitServer() *web.Server {
	configuration := config.GetConfig()
	server := web.NewServer(configuration)
	return server
}

func InitRecordController() *record.Controller {
	db := config.NewDBConnection()
	repository := record.NewRepository(db)
	service := record.NewService(repository)
	controller := record.NewController(service)
	return controller
}
