basePath: /
definitions:
  dto.CreateRecordRequest:
    properties:
      description:
        example: This is description
        type: string
      display_name:
        example: name
        type: string
      url:
        example: /url
        type: string
    required:
    - display_name
    - url
    type: object
  dto.UpdateRecordRequest:
    properties:
      description:
        example: This is a description
        type: string
      display_name:
        example: name
        type: string
      url:
        example: /url
        type: string
    required:
    - display_name
    - url
    type: object
  models.Record:
    properties:
      created_time:
        description: CreatedTime of a record
        example: "2022-10-29T18:31:22.378373+08:00"
        format: date-time
        type: string
      description:
        description: Description of a record
        example: A book to learn Go
        type: string
      display_name:
        description: DisplayName of a record
        example: Learning Go
        type: string
      id:
        description: ID of a record
        example: 1
        type: integer
      updated_time:
        description: UpdatedTime of a record
        example: "2022-10-29T18:31:22.378373+08:00"
        format: date-time
        type: string
      url:
        description: Url of a record
        example: /record/learning-go
        type: string
    type: object
  utils.ErrorMessage:
    properties:
      errors:
        type: string
    type: object
host: localhost:8090
info:
  contact:
    email: Ryan_Wang@epam.com
    name: Ryan_Wang
  description: A simple REST Web service that supports CRUD operations.
  title: Go Web Service
  version: "1.0"
paths:
  /records:
    get:
      description: |-
        Returns a page of records with specified page number and size.<br>
        Currently only supports search by displayName.
      parameters:
      - description: Search by displayName
        in: query
        name: displayName
        type: string
      - description: Page number (default is 0)
        in: query
        name: pageNum
        type: integer
      - description: Page size (default is 10)
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Record'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
      summary: Get records list with pagination and search
      tags:
      - records
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Record Request
        in: body
        name: record
        required: true
        schema:
          $ref: '#/definitions/dto.CreateRecordRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
      summary: Create a record
      tags:
      - records
  /records/{id}:
    delete:
      parameters:
      - description: Delete Record ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
      summary: Delete a record
      tags:
      - records
    get:
      parameters:
      - description: Get Record ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
      summary: Get a record by ID
      tags:
      - records
    put:
      consumes:
      - application/json
      parameters:
      - description: Update Record ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Record Request
        in: body
        name: record
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateRecordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorMessage'
      summary: Update a record
      tags:
      - records
swagger: "2.0"
