// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"git.epam.com/ryan_wang/go-web-service/config"
	"git.epam.com/ryan_wang/go-web-service/internal/controllers"
	"git.epam.com/ryan_wang/go-web-service/internal/repositories"
	"git.epam.com/ryan_wang/go-web-service/internal/services"
	"git.epam.com/ryan_wang/go-web-service/internal/web"
)

// Injectors from wire.go:

func InitServer() *web.Server {
	configuration := config.GetConfig()
	server := web.NewServer(configuration)
	return server
}

func InitRecordController() *controllers.RecordController {
	db := config.NewDBConnection()
	recordRepository := repositories.NewRecordRepository(db)
	recordService := services.NewRecordService(recordRepository)
	recordController := controllers.NewRecordController(recordService)
	return recordController
}
